In [ ]:
import pandas as pd
marks=pd.Series([85,90,78,92,88])
print(marks)

0    85
1    90
2    78
3    92
4    88
dtype: int64

In [ ]:
import pandas as pd
data = {
    'Name': ['Arun', 'Priya', 'Rahul', 'Anu', 'Kiran'],
    'Age': [20, 21, 19, 22, 20],
    'Mark': [85, 90, 78, 92, 88]
}
df=pd.DataFrame(data)
print(df)

    Name  Age  Mark
0   Arun   20    85
1  Priya   21    90
2  Rahul   19    78
3    Anu   22    92
4  Kiran   20    88

In [ ]:
print(df.head(3))

    Name  Age  Mark
0   Arun   20    85
1  Priya   21    90
2  Rahul   19    78

In [ ]:
df.tail(2)

    Name  Age  Mark
3    Anu   22    92
4  Kiran   20    88

In [ ]:
df[['Name']]

    Name
0   Arun
1  Priya
2  Rahul
3    Anu
4  Kiran

In [ ]:
print(df['Mark'] > 50)

0    True
1    True
2    True
3    True
4    True
Name: Mark, dtype: bool

In [ ]:
print(df['Mark'] > 50)

0    True
1    True
2    True
3    True
4    True
Name: Mark, dtype: bool

In [ ]:
df['Grade']='A'
print(df)

    Name  Age  Mark Grade
0   Arun   20    85     A
1  Priya   21    90     A
2  Rahul   19    78     A
3    Anu   22    92     A
4  Kiran   20    88     A

In [ ]:
import pandas as pd
print(df.columns)

Index(['Name', 'Age', 'Mark', 'Grade'], dtype='object')

In [ ]:
import pandas as pd
data = {
    'Name': ['Arun', 'Priya', 'Rahul', 'Anu', 'Kiran'],
    'Age': [20, 21, 19, 22, 20],
    'Mark': [85, 90, 78, 92, 88]
}
df=pd.DataFrame(data)
print(df['Mark'].max())
print(df['Mark'].min())

92
78

In [ ]:
import pandas as pd
data={'Name': ['Arun', 'Priya', 'Rahul', 'Anu', 'Kiran'],
    'Age': [20, 21, 19, 22, 20],
    'Mark': [85, 90, 78, 92, 88]
}
print(df.isnull())

    Name    Age   Mark
0  False  False  False
1  False  False  False
2  False  False  False
3  False  False  False
4  False  False  False

In [ ]:
print(df.isnull().sum())

Name    0
Age     0
Mark    0
dtype: int64

In [ ]:
print(df.sort_values(by='Mark', ascending=False))

    Name  Age  Mark
3    Anu   22    92
1  Priya   21    90
4  Kiran   20    88
0   Arun   20    85
2  Rahul   19    78

In [ ]:
print(len(df))

5

In [ ]:
df = df.drop_duplicates()
print(df)

    Name  Age  Mark
0   Arun   20    85
1  Priya   21    90
2  Rahul   19    78
3    Anu   22    92
4  Kiran   20    88